# Generated by Django 5.1.3 on 2025-05-17 11:48

import core.models.fields.charfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="status",
            field=core.models.fields.charfield.CharField(
                default="disconnected",
                editable=False,
                max_length=255,
                verbose_name="État",
            ),
        ),
    ]
