# Generated by Django 5.1.3 on 2025-08-22 19:01

import core.models.base
import core.models.fields.choice_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
    ]
