# Generated by Django 5.1.3 on 2025-05-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_alter_device_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="log",
            unique_together={("sn", "timestamp", "enroll_id", "in_out")},
        ),
    ]
