# Generated by Django 5.1.3 on 2025-12-14 07:56

import core.models.fields.charfield
import core.models.fields.integerfield
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_alter_device_sub_organization_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ["sn"],
                "verbose_name": "Terminal",
                "verbose_name_plural": "Terminaux",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="geofence_center",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                default=None,
                help_text="Coordonnées (Longitude, Latitude) du centre de la zone de pointage.",
                null=True,
                srid=4326,
                verbose_name="Centre de la Géofence",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="geofence_radius",
            field=core.models.fields.integerfield.IntegerField(
                blank=True,
                default=None,
                help_text="Rayon de la zone de pointage en mètres.",
                null=True,
                verbose_name="Rayon de la Géofence (m)",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=core.models.fields.charfield.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nom de l'appareil"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="sn",
            field=core.models.fields.charfield.CharField(
                max_length=255, unique=True, verbose_name="Numéro de Série"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[("disconnected", "Déconnecté"), ("connected", "Connecté")],
                default="disconnected",
                editable=False,
                max_length=255,
                verbose_name="Statut de connexion",
            ),
        ),
    ]
