# Generated by Django 5.1.3 on 2025-05-17 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_alter_log_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="log",
            constraint=models.UniqueConstraint(
                fields=("sn", "timestamp", "enroll_id", "in_out"),
                name="unique_attendance_log",
            ),
        ),
    ]
