# Generated by Django 5.1.3 on 2025-12-14 11:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_alter_device_options_device_geofence_center_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="geofence_center",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                default=None,
                geography=True,
                help_text="Coordonnées (Longitude, Latitude) du centre de la zone de pointage.",
                null=True,
                srid=4326,
                verbose_name="Centre de la Géofence",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="geofence_center",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                default=None,
                geography=True,
                help_text="Coordonnées (Longitude, Latitude) du centre de la zone de pointage.",
                null=True,
                srid=4326,
                verbose_name="Centre de la Géofence",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="mode",
            field=models.IntegerField(
                choices=[
                    (0, "Fingerprint"),
                    (1, "Card"),
                    (2, "Mot de passe"),
                    (8, "Face"),
                    (10, "Web"),
                ],
                verbose_name="Verification Mode",
            ),
        ),
    ]
