version: '3.8'

services:
  # landlord service (Flask)
  landlord:
    build:
      context: .
      dockerfile: landlord/Dockerfile
    container_name: payday-landlord
    command: >
      sh -c "python manage.py runserver 0.0.0.0:5000"
    ports:
      - "5000:5000"
    volumes:
      - ./landlord:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - master
      - redis
    env_file:
      - prod.env

  # SaaS service (Django)
  saas:
    build:
      context: .
      dockerfile: payday/Dockerfile
    container_name: payday-saas
    restart: unless-stopped
    #command: >
    #  sh -c "python manage.py collectstatic --noinput &&
    #        gunicorn --bind 0.0.0.0:8000 payday.wsgi:application"
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 payday.wsgi:application"
      
    volumes:
      - ./payday:/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - minio-init
      - landlord
      - redis
    env_file:
      - prod.env

  # Nginx service
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: payday-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - saas
      - landlord

  # PostgreSQL master service
  master:
    container_name: payday-master
    image: bitnami/postgresql
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - master_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=slave
      - POSTGRESQL_REPLICATION_PASSWORD=payday
      - POSTGRESQL_USERNAME=master
      - POSTGRESQL_PASSWORD=payday
      - POSTGRESQL_DATABASE=payday
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U master -d payday"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL slave service
  slave:
    container_name: payday-slave
    image: bitnami/postgresql
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - slave_data:/bitnami/postgresql
    depends_on:
      - master
    environment:
      - POSTGRESQL_PASSWORD=payday
      - POSTGRESQL_MASTER_HOST=master
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=slave
      - POSTGRESQL_REPLICATION_PASSWORD=payday
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U slave -h master -d payday"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis service
  redis:
    container_name: payday-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MinIO service
  minio:
    container_name: payday-minio
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_OPTS=--address :9000 --console-address :9001
    command: server /data --address :9000 --console-address ":9001"
    volumes:
      - minio_data:/data
      - ./minio/bucket.sh:/docker-entrypoint-init.d/bucket.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MinIO initialization service
  minio-init:
    build:
      context: .
      dockerfile: minio/Miniofile
    volumes:
      - ./minio:/app
    container_name: payday-minio-init
    depends_on:
      - minio
    environment:
      - MINIO_BUCKET_NAME=payday
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

  # Celery worker service
  worker:
    build: .
    restart: unless-stopped
    container_name: payday-worker
    command: celery -A payday worker -l INFO -E
    volumes:
      - .:/app
    depends_on:
      - saas
    env_file:
      - prod.env
    healthcheck:
      test: ["CMD-SHELL", "celery -A payday inspect ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery beat service
  beat:
    build: .
    restart: unless-stopped
    container_name: payday-beat
    command: celery -A payday beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - master
      - redis
    env_file:
      - prod.env
    healthcheck:
      test: ["CMD-SHELL", "celery -A payday inspect ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - no_auto_start

  # Device service
  device:
    build:
      context: .
      dockerfile: device/Dockerfile
    container_name: payday-device
    restart: unless-stopped
    volumes:
      - ./device:/app
    environment:
      - WEBHOOK_URL=http://web:8000/api/v1/hook/device/
      - BROKER_URL=redis://redis:6379/0
    ports:
      - "7788:7788"
    command: uvicorn device:app --host 0.0.0.0 --port 7788 --workers 4
    depends_on:
      - saas
    profiles:
      - no_auto_start

  # Pubsub service
  pubsub:
    container_name: payday-pubsub
    build: ./pubsub
    depends_on:
      - redis
    ports:
      - "8001:8001"
    environment:
      - AUTH_TOKEN=123456
      - SERVER_PORT=8001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    profiles:
      - no_auto_start

volumes:
  master_data:
  slave_data:
  minio_data: