version: '3.8'

services:
  master:
    image: postgres:latest
    container_name: master
    environment:
      - POSTGRES_PASSWORD=payday
      - POSTGRES_USER=payday
      - POSTGRES_DB=payday
    volumes:
      - ./master-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

  slave:
    image: postgres:latest
    container_name: slave
    environment:
      - POSTGRES_PASSWORD=payday
      - POSTGRES_USER=payday
      - POSTGRES_DB=payday
    depends_on:
      - master
    volumes:
      - ./slave-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: always