version: '3.7'

services:
  master:
    image: postgres:13
    container_name: master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_REPLICATION_ROLE: master
      POSTGRES_REPLICATION_PASSWORD: password
    volumes:
      - ./master-data:/var/lib/postgresql/data
      - ./master-entrypoint.sh:/docker-entrypoint-initdb.d/master-entrypoint.sh
    ports:
      - "5432:5432"
  
  slave:
    image: postgres:13
    container_name: slave
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_REPLICATION_ROLE: replica
      POSTGRES_REPLICATION_PASSWORD: password
    volumes:
      - ./slave-data:/var/lib/postgresql/data
      - ./slave-entrypoint.sh:/docker-entrypoint-initdb.d/slave-entrypoint.sh
    ports:
      - "5433:5432"
    depends_on:
      - master
