version: '3.8'

services:
  wordpress:
    container_name: payday-wordpress
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - prod.env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  mariadb:
    container_name: payday-mariadb
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - prod.env
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    container_name: payday-db
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgbouncer:
    container_name: payday-pgbouncer
    image: edoburu/pgbouncer:latest
    restart: unless-stopped
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    env_file:
      - prod.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "db", "-p", "5432"]
      interval: 30s
      timeout: 10s
      retries: 3

  saas:
    container_name: payday-saas
    build:
      context: .
      dockerfile: payday/Dockerfile
    restart: unless-stopped
    command: sh -c "daphne -b 0.0.0.0 -p 8000 payday.asgi:application"
    volumes:
      - ./payday:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgbouncer
      - redis
    env_file:
      - prod.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    container_name: payday-celery
    build:
      context: .
      dockerfile: payday/Dockerfile
    restart: unless-stopped
    command: celery -A payday worker -l INFO -E
    volumes:
      - ./payday:/app
    depends_on:
      - saas
      - redis
    env_file:
      - prod.env
    healthcheck:
      test: ["CMD", "celery", "-A", "payday", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  flower:
    container_name: payday-flower
    image: mher/flower:latest
    restart: unless-stopped
    command: flower --broker=${CELERY_BROKER_URL} --port=5555
    env_file:
      - prod.env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    container_name: payday-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  lago:
    container_name: payday-lago
    image: getlago/lago:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - prod.env
    depends_on:
      - pgbouncer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  n8n:
    container_name: payday-n8n
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - prod.env
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - pgbouncer
      - redis

  minio:
    container_name: payday-minio
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - prod.env
    command: server /data --address :9000 --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    container_name: payday-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - wordpress
      - saas
      - lago
      - minio
      - celery
      - n8n
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  cmonitor:
    container_name: payday-cmonitor
    image: doormanio/cmonitor:latest
    restart: unless-stopped
    ports:
      - "6000:6000"
    env_file:
      - prod.env
    depends_on:
      - saas
      - wordpress
      - lago
      - nginx
      - db
      - redis
      - minio
      - celery
      - n8n
      - flower
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  certbot:
    container_name: payday-certbot
    build:
      context: .
      dockerfile: certbot/Dockerfile
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/digitalocean.ini:/etc/letsencrypt/digitalocean.ini

volumes:
  wordpress_data:
  postgres_data:
  mariadb_data:
  minio_data:
  n8n_data: