services:
  web:
    build: .
    restart: unless-stopped
    container_name: server
    # command: gunicorn --workers=4 --threads=3 --bind 0.0.0.0:80 payday.wsgi:application
    command: gunicorn --bind 0.0.0.0:80 payday.wsgi:application
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - pgbouncer
      - redis
      - minio
    env_file:
      - .env.server

  worker:
    build: .
    restart: unless-stopped
    container_name: worker
    command: celery -A payday worker -l INFO -E
    volumes:
      - .:/app
    depends_on:
      - pgbouncer
      - redis
      - minio
    env_file:
      - .env.worker

  primary:
    image: postgres:latest
    restart: unless-stopped
    container_name: primary
    volumes:
      - primary:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=primary
      - POSTGRES_USER=payday
      - POSTGRES_PASSWORD=payday

  replica:
    image: postgres:latest
    restart: unless-stopped
    container_name: replica
    volumes:
      - replica:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=replica
      - POSTGRES_USER=payday
      - POSTGRES_PASSWORD=payday
      - POSTGRES_MASTER_USER=payday
      - POSTGRES_MASTER_PASSWORD=payday
      - POSTGRES_MASTER_SERVICE_NAME=primary
    depends_on:
      - primary

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    restart: unless-stopped
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    environment:
      - DB_PASSWORD=payday
      - DB_HOST=primary
      - DB_USER=payday
      - DB_PORT=5432
    depends_on:
      - primary

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_OPTS=--address :9000 --console-address :9001
    command: server /data --address :9000 --console-address ":9001"
    volumes:
      - minio:/data

volumes:
  primary:
  replica:
  minio: