version: '3.9'

services:
  master:
    image: postgres:15
    container_name: master
    environment:
      POSTGRES_USER: payday
      POSTGRES_PASSWORD: payday
      POSTGRES_DB: payday
    volumes:
      - ./postgres/master_data:/var/lib/postgresql/data  # Bind mount for master data
      - ./postgres/master/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payday -h localhost"]
      interval: 10s
      retries: 5

  slave:
    image: postgres:15
    container_name: slave
    environment:
      POSTGRES_USER: payday
      POSTGRES_PASSWORD: payday
      POSTGRES_DB: payday
      REPLICATOR_PASSWORD: replicator_password
    depends_on:
      master:
        condition: service_healthy
    volumes:
      - ./postgres/slave_data:/var/lib/postgresql/data  # Bind mount for slave data
      - ./postgres/slave/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payday -h localhost"]
      interval: 10s
      retries: 5
    entrypoint: ["/docker-entrypoint-initdb.d/entrypoint.sh"]

volumes: {}