version: '3.8'

services:

  master:
    image: postgres:15
    container_name: master
    environment:
      POSTGRES_DB: payday
      POSTGRES_USER: payday
      POSTGRES_PASSWORD: payday
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
      - ./postgres/master/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/master/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./postgres/master/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payday"]
      interval: 10s
      timeout: 5s
      retries: 5

  slave:
    image: postgres:15
    container_name: slave
    environment:
      POSTGRES_DB: payday
      POSTGRES_USER: payday
      POSTGRES_PASSWORD: payday
    ports:
      - "5433:5432"
    depends_on:
      - master
    volumes:
      - slave_data:/var/lib/postgresql/data
      - ./postgres/slave/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    command: ["bash", "/docker-entrypoint-initdb.d/entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payday"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  master_data:
  slave_data:
  # minio: