version: '3'

services:
  master:
    image: postgres:latest
    container_name: master_db
    environment:
      POSTGRES_USER: payday
      POSTGRES_PASSWORD: payday
      POSTGRES_DB: payday
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - master_data:/var/lib/postgresql/data
      - ./init-master.sql:/docker-entrypoint-initdb.d/init-master.sql
    networks:
      - db_network
    ports:
      - "5432:5432"
    restart: always

  slave:
    image: postgres:latest
    container_name: slave_db
    environment:
      POSTGRES_USER: payday
      POSTGRES_PASSWORD: payday
      POSTGRES_DB: payday
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - slave_data:/var/lib/postgresql/data
      - ./init-slave.sql:/docker-entrypoint-initdb.d/init-slave.sql
    networks:
      - db_network
    ports:
      - "5433:5432"
    restart: always

networks:
  db_network:
    driver: bridge

volumes:
  master_data:
  slave_data: