version: '3.8'

services:
  master:
    image: postgres:latest
    container_name: master
    environment:
      - POSTGRES_PASSWORD=payday
      - POSTGRES_USER=payday
      - POSTGRES_DB=payday
    volumes:
      - ./master-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

  slave:
    build:
      context: .
      dockerfile: Dockerfile.slave
    container_name: slave
    environment:
      - POSTGRES_PASSWORD=payday
      - POSTGRES_USER=payday
      - POSTGRES_DB=payday
      - MASTER_HOST=master  # Master database host
      - MASTER_PORT=5432       # Master database port
    depends_on:
      - master
    volumes:
      - slave_data:/var/lib/postgresql/data
      - ./slave-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: always

volumes:
  slave_data: