# Generated by Django 5.1.3 on 2025-01-28 12:31

import core.models.fields.datefield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paidemployee",
            name="date_of_end",
            field=core.models.fields.datefield.DateField(
                blank=True,
                default=None,
                help_text="YYYY-MM-DD",
                null=True,
                verbose_name="date de fin",
            ),
        ),
    ]
