# Generated by Django 5.1.3 on 2025-11-25 14:17

import core.models.base
import core.models.fields.charfield
import core.models.fields.choice_field
import core.models.fields.datefield
import core.models.fields.floatfield
import core.models.fields.integerfield
import core.models.fields.jsonfield
import payroll.models.payroll
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancesalary",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("PENDING", "EN ATTENTE"),
                    ("APPROVED", "APPROUVÉ"),
                    ("REJECTED", "REJETÉ"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="advancesalary",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="advancesalarypayment",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="legalitem",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="attendance",
            field=core.models.fields.integerfield.IntegerField(
                default=0, verbose_name="prestation"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="children",
            field=core.models.fields.integerfield.IntegerField(
                default=0, verbose_name="enfant(s)"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="date_of_end",
            field=core.models.fields.datefield.DateField(
                blank=True,
                default=None,
                help_text="YYYY-MM-DD",
                null=True,
                verbose_name="date de fin du contrat",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="gender",
            field=core.models.fields.charfield.CharField(
                blank=True,
                choices=[("MALE", "HOMME"), ("FEMALE", "FEMME")],
                default=None,
                max_length=10,
                null=True,
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="gross",
            field=core.models.fields.floatfield.FloatField(
                default=0, verbose_name="brut global"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="marital_status",
            field=core.models.fields.charfield.CharField(
                blank=True,
                choices=[
                    ("MARRIED", "MARIÉ"),
                    ("SINGLE", "CÉLIBATAIRE"),
                    ("WIDOWER", "VEUF"),
                    ("DIVORCED", "DIVORCÉ"),
                ],
                default=None,
                max_length=12,
                null=True,
                verbose_name="état civil",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="net",
            field=core.models.fields.floatfield.FloatField(
                default=0, verbose_name="net à payer"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="paid_leave_days",
            field=models.IntegerField(default=0, verbose_name="congé payé (jours)"),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="payment_method",
            field=core.models.fields.charfield.CharField(
                blank=True,
                choices=[
                    ("CASH", "CASH"),
                    ("BANK", "BANK"),
                    ("MOBILE MONEY", "MOBILE MONEY"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="social_security_threshold",
            field=core.models.fields.floatfield.FloatField(
                default=0, verbose_name="plafond CNSS/CNSAP"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="taxable_gross",
            field=core.models.fields.floatfield.FloatField(
                default=0, verbose_name="brut/base imposable"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="unpaid_leave_days",
            field=models.IntegerField(
                default=0, verbose_name="congé sans solde (jours)"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="_metadata",
            field=core.models.fields.jsonfield.JSONField(
                blank=True,
                default=payroll.models.payroll._default_exchange_rate_usd_cdf,
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
    ]
