# Generated by Django 5.1.3 on 2025-06-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_actif",
            field=models.BooleanField(
                default=True,
                help_text="Cet élément est actif",
                verbose_name="est actif",
            ),
        ),
        migrations.AddField(
            model_name="legalitem",
            name="is_actif",
            field=models.BooleanField(
                default=True,
                help_text="Cet élément est actif",
                verbose_name="est actif",
            ),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="is_payable",
            field=models.BooleanField(
                default=True,
                help_text="Cet élément est payable et comptabilisable, mais il n'est pas liquide.",
                verbose_name="est payable",
            ),
        ),
    ]
