# Generated by Django 5.1.3 on 2025-02-02 08:51

import core.models.fields.integerfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paidemployee",
            name="children",
            field=core.models.fields.integerfield.IntegerField(
                default=0, verbose_name="children"
            ),
        ),
        migrations.AddField(
            model_name="paidemployee",
            name="working_days_per_month",
            field=core.models.fields.integerfield.IntegerField(
                default=23, verbose_name="jours ouvrables par mois"
            ),
        ),
    ]
