# Generated by Django 5.1.3 on 2025-06-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_item_is_actif_legalitem_is_actif_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancesalary",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "EN ATTENTE"),
                    ("APPROVED", "APPROUVÉ"),
                    ("REJECTED", "REJETÉ"),
                ],
                default="PENDING",
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "créé"),
                    ("ON_HOLD", "en attente"),
                    ("IN_PROGRESS", "en cours"),
                    ("COMPLETED", "terminé"),
                    ("ERROR", "erreur"),
                    ("APPROVED", "APPROUVÉ"),
                    ("REJECTED", "REJETÉ"),
                ],
                default="CREATED",
                editable=False,
                max_length=25,
                verbose_name="état",
            ),
        ),
    ]
