# Generated by Django 5.1.3 on 2025-05-13 16:46

import core.models.fields.charfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_paidemployee_children_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paidemployee",
            name="marital_status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("MARRIED", "MARIÉ"),
                    ("SINGLE", "CÉLIBATAIRE"),
                    ("WIDOWER", "VEUF"),
                    ("DIVORCED", "DIVORCÉ"),
                ],
                max_length=12,
                verbose_name="état civil",
            ),
        ),
    ]
