# Generated by Django 5.1.3 on 2025-01-05 16:56

import core.models.fields.charfield
import core.models.fields.foreignkey
import core.models.fields.model_select_field
import core.models.fields.model_select_to_multiple_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="content_type",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                help_text="Le modèle auquel cette permission est associée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="user",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                help_text="L'utilisateur auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de sécurité est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rows",
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="user",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                help_text="L'utilisateur auquel cette règle de sécurité s'applique.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                blank=True,
                help_text="Permissions spécifiques à cet utilisateur.",
                to="auth.permission",
                verbose_name="permissions de l’utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="content_type",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=150, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "permissions",
                    core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                        blank=True,
                        related_name="groups",
                        to="auth.permission",
                        verbose_name="permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
            },
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="group",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                help_text="Le groupe auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.group",
                verbose_name="roles",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="group",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                help_text="Le groupe auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.group",
                verbose_name="roles",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                blank=True,
                help_text="Les groupes dont fait partie cet utilisateur. Celui-ci obtient tous les droits de tous les groupes auxquels il appartient.",
                to="core.group",
                verbose_name="groupes",
            ),
        ),
    ]
