# Generated by Django 5.1.3 on 2025-01-05 18:02

import core.models.fields.charfield
import core.models.fields.foreignkey
import core.models.fields.model_select_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0004_alter_fieldpermission_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldpermission",
            name="content_type",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                help_text="Le modèle auquel cette permission est associée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="field",
            field=core.models.fields.charfield.CharField(
                help_text="Le nom du champ pour lequel la permission est définie.",
                max_length=100,
                verbose_name="champ",
            ),
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="group",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                help_text="Le groupe auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.group",
                verbose_name="roles",
            ),
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="user",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                help_text="L'utilisateur auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de sécurité est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rows",
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="group",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                help_text="Le groupe auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.group",
                verbose_name="roles",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="user",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                help_text="L'utilisateur auquel cette règle de sécurité s'applique.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="content_type",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalUser",
        ),
    ]
