# Generated by Django 5.1.3 on 2025-01-14 14:04

import core.models.fields.foreignkey
import core.models.fields.model_select_field
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0005_alter_fieldpermission_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldpermission",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="group",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                help_text="Le groupe auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.group",
                verbose_name="roles",
            ),
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="user",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                help_text="L'utilisateur auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="group",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                help_text="Le groupe auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.group",
                verbose_name="roles",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="user",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                help_text="L'utilisateur auquel cette règle de sécurité s'applique.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="content_type",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
    ]
