# Generated by Django 5.1.3 on 2025-01-06 12:21

import core.models.fields.booleanfield
import core.models.fields.charfield
import core.models.fields.foreignkey
import core.models.fields.model_select_field
import core.models.fields.textfield
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0006_remove_historicalwidget_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldpermission",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="group",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                help_text="Le groupe auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.group",
                verbose_name="roles",
            ),
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="user",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                help_text="L'utilisateur auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="message",
            field=core.models.fields.textfield.TextField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="message",
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("processing", "en cours"),
                    ("pending", "en attente"),
                    ("success", "succès"),
                    ("error", "erreur"),
                ],
                default="pending",
                editable=False,
                max_length=255,
                verbose_name="état",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="_from",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="de",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="_to",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="à",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=core.models.fields.textfield.TextField(
                editable=False, verbose_name="message"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="redirect",
            field=core.models.fields.charfield.CharField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                verbose_name="rediriger vers",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="subject",
            field=core.models.fields.charfield.CharField(
                editable=False, max_length=255, verbose_name="sujet"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="viewed",
            field=core.models.fields.booleanfield.BooleanField(
                default=False, editable=False, verbose_name="vu"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="group",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                help_text="Le groupe auquel cette permission est attribuée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.group",
                verbose_name="roles",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="user",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                help_text="L'utilisateur auquel cette règle de sécurité s'applique.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                editable=False, max_length=128, verbose_name="mot de passe"
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="content_type",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
    ]
