# Generated by Django 5.1.3 on 2025-06-29 06:32

import core.models.base
import core.models.fields.booleanfield
import core.models.fields.charfield
import core.models.fields.choice_field
import core.models.fields.datefield
import core.models.fields.datetimefield
import core.models.fields.emailfield
import core.models.fields.filefield
import core.models.fields.imagefield
import core.models.fields.integerfield
import core.models.fields.jsonfield
import core.models.fields.model_select_field
import core.models.fields.model_select_to_multiple_field
import core.models.fields.onetoonefield
import core.models.fields.textfield
import core.utils.upload_directory_file
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import employee.models.employee
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "checked_at",
                    core.models.fields.datetimefield.DateTimeField(
                        verbose_name="vérifié à"
                    ),
                ),
                (
                    "first_checked_at",
                    core.models.fields.datetimefield.DateTimeField(
                        verbose_name="check-in à"
                    ),
                ),
                (
                    "last_checked_at",
                    core.models.fields.datetimefield.DateTimeField(
                        verbose_name="check-out à"
                    ),
                ),
                (
                    "count",
                    core.models.fields.integerfield.IntegerField(
                        verbose_name="presence"
                    ),
                ),
            ],
            options={
                "verbose_name": "presence",
                "verbose_name_plural": "presences",
                "db_table": "employee_attendance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "group",
                    core.models.fields.charfield.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="groupe",
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=100, unique=True, verbose_name="nom"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "contrat",
                "verbose_name_plural": "contrats",
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "group",
                    core.models.fields.charfield.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="groupe",
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=100, unique=True, verbose_name="nom"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "site",
                "verbose_name_plural": "sites",
            },
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "group",
                    core.models.fields.charfield.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="groupe",
                    ),
                ),
                (
                    "working_days_per_month",
                    core.models.fields.integerfield.IntegerField(
                        default=23, verbose_name="jours ouvrables par mois"
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=100, unique=True, verbose_name="nom"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "position",
                "verbose_name_plural": "positions",
            },
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=100, unique=True, verbose_name="nom"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "direction",
                "verbose_name_plural": "directions",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "social_security_number",
                    core.models.fields.charfield.CharField(
                        blank=True,
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="numéro de sécurité sociale",
                    ),
                ),
                (
                    "date_of_join",
                    core.models.fields.datefield.DateField(
                        default=None,
                        help_text="YYYY-MM-DD",
                        null=True,
                        verbose_name="date d'engagement",
                    ),
                ),
                (
                    "date_of_end",
                    core.models.fields.datefield.DateField(
                        blank=True,
                        default=None,
                        help_text="YYYY-MM-DD",
                        null=True,
                        verbose_name="date de fin",
                    ),
                ),
                (
                    "middle_name",
                    core.models.fields.charfield.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="post-nom",
                    ),
                ),
                (
                    "first_name",
                    core.models.fields.charfield.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="prénom",
                    ),
                ),
                (
                    "last_name",
                    core.models.fields.charfield.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="nom",
                    ),
                ),
                (
                    "date_of_birth",
                    core.models.fields.datefield.DateField(
                        default=None,
                        help_text="YYYY-MM-DD",
                        null=True,
                        verbose_name="date de naissance",
                    ),
                ),
                (
                    "gender",
                    core.models.fields.charfield.CharField(
                        choices=[("MALE", "HOMME"), ("FEMALE", "FEMME")],
                        max_length=10,
                        verbose_name="genre",
                    ),
                ),
                (
                    "spouse_date_of_birth",
                    core.models.fields.datefield.DateField(
                        blank=True,
                        default=None,
                        help_text="YYYY-MM-DD",
                        null=True,
                        verbose_name="date de naissance du conjoint",
                    ),
                ),
                (
                    "spouse",
                    core.models.fields.charfield.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="conjoint",
                    ),
                ),
                (
                    "marital_status",
                    core.models.fields.charfield.CharField(
                        choices=[
                            ("MARRIED", "MARIÉ"),
                            ("SINGLE", "CÉLIBATAIRE"),
                            ("WIDOWER", "VEUF"),
                            ("DIVORCED", "DIVORCÉ"),
                        ],
                        max_length=12,
                        verbose_name="état civil",
                    ),
                ),
                (
                    "mobile_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default=None,
                        help_text="+243 XXX XXX XXX",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="numéro de téléphone mobile",
                    ),
                ),
                (
                    "physical_address",
                    core.models.fields.textfield.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="adresse physique",
                    ),
                ),
                (
                    "emergency_information",
                    core.models.fields.textfield.TextField(
                        default=None, null=True, verbose_name="informations d'urgence"
                    ),
                ),
                (
                    "payment_account",
                    core.models.fields.charfield.CharField(
                        blank=True,
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="numéro de compte/paiement",
                    ),
                ),
                (
                    "payment_method",
                    core.models.fields.charfield.CharField(
                        choices=[
                            ("CASH", "CASH"),
                            ("BANK", "BANK"),
                            ("MOBILE MONEY", "MOBILE MONEY"),
                        ],
                        max_length=20,
                        verbose_name="mode de paiement",
                    ),
                ),
                (
                    "payer_name",
                    core.models.fields.charfield.CharField(
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="nom du payeur",
                    ),
                ),
                (
                    "comment",
                    core.models.fields.textfield.TextField(
                        blank=True, default=None, null=True, verbose_name="commentaire"
                    ),
                ),
                (
                    "create_user_on_save",
                    core.models.fields.booleanfield.BooleanField(
                        default=False,
                        help_text="Créez un utilisateur pour cet employé si l'adresse e-mail est fournie.",
                        verbose_name="créer un utilisateur",
                    ),
                ),
                (
                    "photo",
                    core.models.fields.imagefield.ImageField(
                        blank=True,
                        help_text="Photo passport de format standard, MAX 1MB",
                        null=True,
                        upload_to=core.utils.upload_directory_file,
                        verbose_name="photo",
                    ),
                ),
                (
                    "registration_number",
                    core.models.fields.charfield.CharField(
                        default=employee.models.employee.default_registration_number,
                        max_length=50,
                        verbose_name="matricule",
                    ),
                ),
                (
                    "email",
                    core.models.fields.emailfield.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "agreement",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.agreement",
                        verbose_name="type de contrat",
                    ),
                ),
                (
                    "branch",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.branch",
                        verbose_name="site",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "designation",
                    core.models.fields.model_select_field.ModelSelectField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.designation",
                        verbose_name="fonction",
                    ),
                ),
                (
                    "devices",
                    core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                        blank=True,
                        help_text="Veuillez choisir les terminaux de présence que l'agent utilisera pour pointer.",
                        to="device.device",
                        verbose_name="terminaux",
                    ),
                ),
                (
                    "direction",
                    core.models.fields.model_select_field.ModelSelectField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.direction",
                        verbose_name="direction",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    core.models.fields.onetoonefield.OneToOneField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "employé",
                "verbose_name_plural": "employés",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "institution",
                    core.models.fields.charfield.CharField(
                        max_length=255, verbose_name="institution"
                    ),
                ),
                (
                    "degree",
                    core.models.fields.charfield.CharField(
                        max_length=255, verbose_name="diplôme"
                    ),
                ),
                (
                    "start_date",
                    core.models.fields.datefield.DateField(
                        blank=True, null=True, verbose_name="date de début"
                    ),
                ),
                (
                    "end_date",
                    core.models.fields.datefield.DateField(
                        blank=True, null=True, verbose_name="date de fin"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "education",
                "verbose_name_plural": "educations",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "document",
                    core.models.fields.filefield.FileField(
                        upload_to=core.utils.upload_directory_file,
                        verbose_name="nom du document",
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=100, verbose_name="nom du document"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "full_name",
                    core.models.fields.charfield.CharField(
                        max_length=100, verbose_name="nom complet"
                    ),
                ),
                (
                    "date_of_birth",
                    core.models.fields.datefield.DateField(
                        verbose_name="date de naissance"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "enfant",
                "verbose_name_plural": "enfants",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "group",
                    core.models.fields.charfield.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="groupe",
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=100, unique=True, verbose_name="nom"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "grade",
                "verbose_name_plural": "grades",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="grade",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.grade",
                verbose_name="grade",
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=100, unique=True, verbose_name="nom"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="service",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.service",
                verbose_name="service",
            ),
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "group",
                    core.models.fields.charfield.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="groupe",
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=100, unique=True, verbose_name="nom"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "état",
                "verbose_name_plural": "état",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.status",
                verbose_name="état",
            ),
        ),
        migrations.CreateModel(
            name="SubDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_category_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organization",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "direction",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.direction",
                        verbose_name="direction",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "sous-direction",
                "verbose_name_plural": "sous-directions",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="subdirection",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.subdirection",
                verbose_name="sous-direction",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="subdirection",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.subdirection",
                verbose_name="sous-direction",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("sub_organization", "registration_number")},
        ),
    ]
