# Generated by Django 5.1.3 on 2025-01-14 14:27

import core.models.fields.charfield
import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="branch",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.branch",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="device",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.device",
                verbose_name="dispositif",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
                verbose_name="employé",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="sn",
            field=core.models.fields.charfield.CharField(
                editable=False,
                max_length=255,
                unique=True,
                verbose_name="Serial Number",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[("disconnected", "Disconnected"), ("connected", "Connected")],
                default="disconnected",
                editable=False,
                max_length=255,
                verbose_name="État",
            ),
        ),
    ]
