# Generated by Django 5.1.3 on 2025-08-22 19:01

import core.models.base
import core.models.fields.charfield
import core.models.fields.choice_field
import core.models.fields.datefield
import core.models.fields.integerfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_create_attendance_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="working_days_per_month",
            field=core.models.fields.integerfield.IntegerField(
                default=22, verbose_name="jours ouvrables par mois"
            ),
        ),
        migrations.AlterField(
            model_name="direction",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_of_end",
            field=core.models.fields.datefield.DateField(
                blank=True,
                default=None,
                help_text="YYYY-MM-DD",
                null=True,
                verbose_name="date de fin du contrat",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=core.models.fields.charfield.CharField(
                blank=True,
                choices=[("MALE", "HOMME"), ("FEMALE", "FEMME")],
                default=None,
                max_length=10,
                null=True,
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=core.models.fields.charfield.CharField(
                blank=True,
                choices=[
                    ("MARRIED", "MARIÉ"),
                    ("SINGLE", "CÉLIBATAIRE"),
                    ("WIDOWER", "VEUF"),
                    ("DIVORCED", "DIVORCÉ"),
                ],
                default=None,
                max_length=12,
                null=True,
                verbose_name="état civil",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="payment_method",
            field=core.models.fields.charfield.CharField(
                blank=True,
                choices=[
                    ("CASH", "CASH"),
                    ("BANK", "BANK"),
                    ("MOBILE MONEY", "MOBILE MONEY"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="subdirection",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
    ]
