# Generated by Django 5.1.3 on 2025-01-19 12:40

import core.models.fields.datetimefield
import core.models.fields.model_select_field
import core.models.fields.model_select_to_multiple_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_device_branch_alter_attendance_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="devices",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                to="employee.device", verbose_name="terminaux"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="checked_at",
            field=core.models.fields.datetimefield.DateTimeField(
                editable=False, verbose_name="vérifié à"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="device",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.device",
                verbose_name="dispositif",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
                verbose_name="employé",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="branch",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.branch",
                verbose_name="site",
            ),
        ),
    ]
