# Generated by Django 5.1.3 on 2025-01-20 08:53

import core.models.fields.model_select_field
import core.models.fields.model_select_to_multiple_field
import core.models.fields.photopreviewfield
import core.utils.upload_directory_file
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_employee_devices_alter_attendance_checked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="device",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.device",
                verbose_name="dispositif",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
                verbose_name="employé",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="branch",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.branch",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="devices",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                help_text="Veuillez choisir les terminaux de présence que l'agent utilisera pour pointer.",
                to="employee.device",
                verbose_name="terminaux",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=core.models.fields.photopreviewfield.PhotoPreviewField(
                blank=True,
                null=True,
                upload_to=core.utils.upload_directory_file,
                verbose_name="photo",
            ),
        ),
    ]
