# Generated by Django 5.1.3 on 2025-05-13 16:46

import core.models.fields.charfield
import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_alter_attendance_employee_alter_device_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.designation",
                verbose_name="fonction",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("MARRIED", "MARIÉ"),
                    ("SINGLE", "CÉLIBATAIRE"),
                    ("WIDOWER", "VEUF"),
                    ("DIVORCED", "DIVORCÉ"),
                ],
                max_length=12,
                verbose_name="état civil",
            ),
        ),
    ]
