# Generated by Django 5.1.3 on 2025-01-27 13:33

import core.models.fields.charfield
import core.models.fields.imagefield
import core.models.fields.model_select_field
import core.models.fields.model_select_to_multiple_field
import core.utils.upload_directory_file
import django.db.models.deletion
import employee.models.employee
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_alter_attendance_device_alter_attendance_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="device",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.device",
                verbose_name="dispositif",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
                verbose_name="employé",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="branch",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.branch",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="devices",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                blank=True,
                help_text="Veuillez choisir les terminaux de présence que l'agent utilisera pour pointer.",
                to="employee.device",
                verbose_name="terminaux",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=core.models.fields.imagefield.ImageField(
                blank=True,
                null=True,
                upload_to=core.utils.upload_directory_file,
                verbose_name="photo",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="registration_number",
            field=core.models.fields.charfield.CharField(
                default=employee.models.employee.default_registration_number,
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="matricule",
            ),
        ),
    ]
