# Generated by Django 5.1.3 on 2025-01-27 14:04

import core.models.fields.charfield
import core.models.fields.datefield
import core.models.fields.datetimefield
import core.models.fields.filefield
import core.models.fields.jsonfield
import core.models.fields.model_select_field
import core.utils.upload_directory_file
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_alter_attendance_employee_alter_device_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name": "presence", "verbose_name_plural": "presences"},
        ),
        migrations.AlterField(
            model_name="attendance",
            name="device",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.device",
                verbose_name="dispositif",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
                verbose_name="employé",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="branch",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.branch",
                verbose_name="site",
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "document",
                    core.models.fields.filefield.FileField(
                        upload_to=core.utils.upload_directory_file,
                        verbose_name="certificat de naissance",
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=100, verbose_name="nom du document"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "institution",
                    core.models.fields.charfield.CharField(
                        max_length=255, verbose_name="institution"
                    ),
                ),
                (
                    "degree",
                    core.models.fields.charfield.CharField(
                        max_length=255, verbose_name="diplôme"
                    ),
                ),
                (
                    "start_date",
                    core.models.fields.datefield.DateField(
                        blank=True, null=True, verbose_name="date de début"
                    ),
                ),
                (
                    "end_date",
                    core.models.fields.datefield.DateField(
                        blank=True, null=True, verbose_name="date de fin"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "education",
                "verbose_name_plural": "educations",
            },
        ),
    ]
