# Generated by Django 5.1.3 on 2025-01-27 14:05

import core.models.fields.filefield
import core.models.fields.model_select_field
import core.utils.upload_directory_file
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_alter_attendance_options_alter_attendance_device_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="birth_certificate",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="device",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.device",
                verbose_name="dispositif",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
                verbose_name="employé",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="branch",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.branch",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document",
            field=core.models.fields.filefield.FileField(
                upload_to=core.utils.upload_directory_file,
                verbose_name="nom du document",
            ),
        ),
    ]
