# Generated by Django 5.1.3 on 2025-01-28 12:10

import core.models.fields.charfield
import core.models.fields.datetimefield
import core.models.fields.model_select_field
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_remove_child_birth_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="group",
            field=core.models.fields.charfield.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="groupe",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="group",
            field=core.models.fields.charfield.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="groupe",
            ),
        ),
        migrations.AddField(
            model_name="designation",
            name="group",
            field=core.models.fields.charfield.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="groupe",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="group",
            field=core.models.fields.charfield.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="groupe",
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="group",
            field=core.models.fields.charfield.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="groupe",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="checked_at",
            field=core.models.fields.datetimefield.DateTimeField(
                verbose_name="vérifié à"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="device",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.device",
                verbose_name="dispositif",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
                verbose_name="employé",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="branch",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.branch",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="sn",
            field=core.models.fields.charfield.CharField(
                max_length=255, unique=True, verbose_name="Serial Number"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=core.models.fields.charfield.CharField(
                choices=[("MALE", "HOMME"), ("FEMALE", "FEMME")],
                max_length=10,
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("MARIED", "MARIÉ"),
                    ("SINGLE", "CÉLIBATAIRE"),
                    ("WIDOWER", "VEUF"),
                    ("DIVORCED", "DIVORCÉ"),
                ],
                max_length=12,
                verbose_name="état civil",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="mobile_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None,
                help_text="+243 XXX XXX XXX",
                max_length=128,
                null=True,
                region=None,
                verbose_name="numéro de téléphone mobile",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="payment_method",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("CASH", "CASH"),
                    ("BANK", "BANK"),
                    ("MOBILE MONEY", "MOBILE MONEY"),
                ],
                max_length=20,
                verbose_name="mode de paiement",
            ),
        ),
    ]
