# Generated by Django 5.1.3 on 2025-01-28 12:31

import core.models.fields.datefield
import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_agreement_group_branch_group_designation_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_of_end",
            field=core.models.fields.datefield.DateField(
                blank=True,
                default=None,
                help_text="YYYY-MM-DD",
                null=True,
                verbose_name="date de fin",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="device",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.device",
                verbose_name="dispositif",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
                verbose_name="employé",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="branch",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.branch",
                verbose_name="site",
            ),
        ),
    ]
