http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        stsSeconds: 31536000
        contentTypeNosniff: true
        browserXssFilter: true
    gzip:
      compress: {}
    websocket-headers:
      headers:
        customRequestHeaders:
          Upgrade: "websocket"
          Connection: "upgrade"
        customResponseHeaders:
          Upgrade: "websocket"
          Connection: "upgrade"
    large-body:
      buffering:
        maxRequestBodyBytes: 100000000