global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    transport:
      respondingTimeouts:
        readTimeout: 0
        writeTimeout: 0
        idleTimeout: 0

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: payday-saas_traefik-net
    constraints: "!Label(`traefik.enable`, `false`)"

log:
  level: DEBUG