global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: bridge
  file:
    filename: /etc/traefik/dynamic.yml

log:
  level: INFO

accessLog: {}