# Generated by Django 5.1.3 on 2025-01-18 09:11

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="nom")),
                ("schema", models.CharField(max_length=50, verbose_name="schema")),
                ("email", models.EmailField(max_length=50, verbose_name="email")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="phone"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(max_length=50, verbose_name="is active"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
            ],
            options={
                "verbose_name": "tenant",
                "verbose_name_plural": "tenant(s)",
            },
        ),
    ]
