# Generated by Django 5.1.3 on 2025-02-18 11:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="votre prénom"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="votre nom"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="nom de l'organisme"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=50, unique=True, verbose_name="email"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="+243 8XX XXX XXX",
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="numéro de téléphone mobile",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            (
                                '{"name": "basic", "description": "Essentielle", "price": 0, "currency": "USD", "apps": {"employee": {"max": 100}, "payroll": {"max": 1}}}',
                                "Essentielle",
                            )
                        ],
                        default='{"name": "basic", "description": "Essentielle", "price": 0, "currency": "USD", "apps": {"employee": {"max": 100}, "payroll": {"max": 1}}}',
                        max_length=255,
                        verbose_name="plan d'abonnement",
                    ),
                ),
                (
                    "schema",
                    models.CharField(
                        editable=False,
                        help_text="Nom du schéma dans la base de données",
                        max_length=50,
                        unique=True,
                        verbose_name="schéma",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Définir si le compte est actif ou non",
                        verbose_name="est actif",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
            ],
            options={
                "verbose_name": "tenant",
                "verbose_name_plural": "tenant(s)",
                "unique_together": {("name", "phone")},
            },
        ),
    ]
