# Generated by Django 5.1.3 on 2025-01-27 22:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="votre prenom"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="votre nom"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="nom de l'organisme"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=50, unique=True, verbose_name="email"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="+243 8XX XXX XXX",
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="numéro de téléphone mobile",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("trail", "Essai"),
                            ("basic", "Basique"),
                            ("premium", "Premium"),
                            ("enterprise", "Entreprise"),
                        ],
                        default="basic",
                        max_length=50,
                        verbose_name="plan d'abonnement",
                    ),
                ),
                (
                    "schema",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="schema",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="is active"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
            ],
            options={
                "verbose_name": "tenant",
                "verbose_name_plural": "tenant(s)",
                "db_table": "tenant",
                "unique_together": {("name", "phone")},
            },
        ),
    ]
