# Generated by Django 5.1.3 on 2025-02-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="_plan",
            field=models.JSONField(
                choices=[("Essentielle", [("name", "basic"), ("max", 5)])],
                default=dict,
                editable=False,
                verbose_name="plan d'abonnement",
            ),
        ),
    ]
