# Generated by Django 5.1.3 on 2025-01-18 14:26

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="first_name",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, verbose_name="prénom"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="last_name",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, verbose_name="nom"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenant",
            name="size",
            field=models.CharField(
                choices=[
                    (None, "-"),
                    ("1-10", "1-10"),
                    ("11-50", "11-50"),
                    ("51-200", "51-200"),
                    ("201-500", "201-500"),
                    ("501-1000", "501-1000"),
                    ("1001+", "1001+"),
                ],
                default=django.utils.timezone.now,
                help_text="This information helps us tailor our services to better meet your needs.",
                max_length=50,
                verbose_name="size of organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(
                default=False, editable=False, max_length=50, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(max_length=50, verbose_name="organization's name"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="+243 8XX XXX XXX",
                max_length=128,
                region=None,
                verbose_name="phone",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="schema",
            field=models.CharField(
                editable=False, max_length=50, verbose_name="schema"
            ),
        ),
    ]
