# Generated by Django 5.1.3 on 2025-02-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0002_tenant__plan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="_plan",
            new_name="planer",
        ),
    ]
