# Generated by Django 5.1.3 on 2025-01-27 21:54

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0002_tenant_first_name_tenant_last_name_tenant_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                choices=[
                    ("trail", "Essai"),
                    ("basic", "Basique"),
                    ("premium", "Premium"),
                    ("enterprise", "Entreprise"),
                ],
                default="basic",
                max_length=50,
                verbose_name="plan d'abonnement",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="email",
            field=models.EmailField(max_length=50, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="votre prenom"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="votre nom"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="nom de l'organisme"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="+243 8XX XXX XXX",
                max_length=128,
                region=None,
                unique=True,
                verbose_name="numéro de téléphone mobile",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="schema",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="schema"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="size",
            field=models.CharField(
                choices=[
                    (None, "-"),
                    ("1-10", "1-10"),
                    ("11-50", "11-50"),
                    ("51-200", "51-200"),
                    ("201-500", "201-500"),
                    ("501-1000", "501-1000"),
                    ("1001+", "1001+"),
                ],
                help_text="This information helps us tailor our services to better meet your needs.",
                max_length=50,
                verbose_name="taille de l'organisation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenant",
            unique_together={("name", "phone")},
        ),
        migrations.AlterModelTable(
            name="tenant",
            table="tenant",
        ),
    ]
