# Generated by Django 5.1.3 on 2025-02-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0003_rename__plan_tenant_planer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="planer",
        ),
        migrations.AlterField(
            model_name="tenant",
            name="plan",
            field=models.CharField(
                choices=[
                    (
                        '{"name": "basic", "description": "Essentielle", "price": 0, "currency": "USD", "apps": {"employee": {"max": 100}, "payroll": {"max": 1}}}',
                        "Essentielle",
                    )
                ],
                default='{"name": "basic", "description": "Essentielle", "price": 0, "currency": "USD", "apps": {"employee": {"max": 100}, "payroll": {"max": 1}}}',
                max_length=255,
                verbose_name="plan d'abonnement",
            ),
        ),
    ]
