# Generated by Django 5.1.3 on 2025-02-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0004_remove_tenant_planer_alter_tenant_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="is active"),
        ),
    ]
