# Generated by Django 5.1.3 on 2025-02-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0005_alter_tenant_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Définir si le compte est actif ou non",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="schema",
            field=models.CharField(
                editable=False,
                help_text="Nom du schéma dans la base de données",
                max_length=50,
                unique=True,
                verbose_name="schema",
            ),
        ),
    ]
