version: '3'
services:
  websocket:
    build: .
    environment:
      - AUTH_TOKEN=PourSomeSugarOnMe
    ports:
      - 8000:8000
    depends_on:
      - "redis"
  redis:
    image: redis
    ports:
      - 6379
