# Generated by Django 5.1.3 on 2025-05-22 09:53

import core.models.fields.charfield
import core.models.fields.datefield
import core.models.fields.datetimefield
import core.models.fields.jsonfield
import core.models.fields.model_select_field
import core.models.fields.positiveintegerfield
import core.models.fields.textfield
import core.models.fields.timefield
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EarlyLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "date",
                    core.models.fields.datefield.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="date du départ anticipé",
                    ),
                ),
                (
                    "start_time",
                    core.models.fields.timefield.TimeField(
                        verbose_name="heure de début"
                    ),
                ),
                (
                    "end_time",
                    core.models.fields.timefield.TimeField(verbose_name="heure de fin"),
                ),
                (
                    "reason",
                    core.models.fields.textfield.TextField(
                        blank=True, verbose_name="motif"
                    ),
                ),
                (
                    "status",
                    core.models.fields.charfield.CharField(
                        choices=[
                            ("pending", "en attente"),
                            ("approved", "approuvé"),
                            ("rejected", "rejeté"),
                        ],
                        default="pending",
                        editable=False,
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "départ anticipé",
                "verbose_name_plural": "départs anticipés",
            },
        ),
        migrations.CreateModel(
            name="TypeOfLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=100, verbose_name="type de congé"
                    ),
                ),
                (
                    "description",
                    core.models.fields.textfield.TextField(
                        blank=True, verbose_name="description"
                    ),
                ),
                (
                    "min_duration",
                    core.models.fields.positiveintegerfield.PositiveIntegerField(
                        default=1, verbose_name="durée minimale (jours)"
                    ),
                ),
                (
                    "max_duration",
                    core.models.fields.positiveintegerfield.PositiveIntegerField(
                        default=30, verbose_name="durée maximale (jours)"
                    ),
                ),
                (
                    "eligibility_after_days",
                    core.models.fields.positiveintegerfield.PositiveIntegerField(
                        default=30, verbose_name="délai avant d'être éligible (jours)"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "type de congé",
                "verbose_name_plural": "types de congé",
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "reason",
                    core.models.fields.textfield.TextField(
                        blank=True, verbose_name="motif"
                    ),
                ),
                (
                    "start_date",
                    core.models.fields.datefield.DateField(
                        verbose_name="date de début"
                    ),
                ),
                (
                    "end_date",
                    core.models.fields.datefield.DateField(verbose_name="date de fin"),
                ),
                (
                    "status",
                    core.models.fields.charfield.CharField(
                        choices=[
                            ("pending", "en attente"),
                            ("approved", "approuvé"),
                            ("rejected", "rejeté"),
                        ],
                        default="pending",
                        editable=False,
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
                (
                    "type_of_leave",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leave.typeofleave",
                        verbose_name="type de congé",
                    ),
                ),
            ],
            options={
                "verbose_name": "congé",
                "verbose_name_plural": "congés",
            },
        ),
    ]
