# Generated by Django 5.1.3 on 2026-01-06 12:54

import core.models.base
import core.models.fields.booleanfield
import core.models.fields.charfield
import core.models.fields.choice_field
import core.models.fields.datefield
import core.models.fields.datetimefield
import core.models.fields.jsonfield
import core.models.fields.model_select_field
import core.models.fields.positiveintegerfield
import core.models.fields.textfield
import core.models.fields.timefield
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employee", "0003_alter_agreement_sub_organization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EarlyLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_sub_organization_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organisation",
                    ),
                ),
                (
                    "status",
                    core.models.fields.charfield.CharField(
                        choices=[
                            ("PENDING", "EN ATTENTE"),
                            ("APPROVED", "APPROUVÉ"),
                            ("REJECTED", "REJETÉ"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "date",
                    core.models.fields.datefield.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="date du départ anticipé",
                    ),
                ),
                (
                    "start_time",
                    core.models.fields.timefield.TimeField(
                        verbose_name="heure de début"
                    ),
                ),
                (
                    "end_time",
                    core.models.fields.timefield.TimeField(verbose_name="heure de fin"),
                ),
                (
                    "reason",
                    core.models.fields.textfield.TextField(
                        blank=True, verbose_name="motif"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "départ anticipé",
                "verbose_name_plural": "départs anticipés",
            },
        ),
        migrations.CreateModel(
            name="TypeOfLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_sub_organization_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organisation",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=100, verbose_name="type de congé"
                    ),
                ),
                (
                    "description",
                    core.models.fields.textfield.TextField(
                        blank=True, verbose_name="description"
                    ),
                ),
                (
                    "min_duration",
                    core.models.fields.positiveintegerfield.PositiveIntegerField(
                        default=1, verbose_name="durée minimale (jours)"
                    ),
                ),
                (
                    "max_duration",
                    core.models.fields.positiveintegerfield.PositiveIntegerField(
                        default=30, verbose_name="durée maximale (jours)"
                    ),
                ),
                (
                    "eligibility_after_days",
                    core.models.fields.positiveintegerfield.PositiveIntegerField(
                        default=30, verbose_name="délai avant d'être éligible (jours)"
                    ),
                ),
                (
                    "paid",
                    core.models.fields.booleanfield.BooleanField(
                        default=True, verbose_name="congé payé"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "type de congé",
                "verbose_name_plural": "types de congé",
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_sub_organization_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organisation",
                    ),
                ),
                (
                    "status",
                    core.models.fields.charfield.CharField(
                        choices=[
                            ("PENDING", "EN ATTENTE"),
                            ("APPROVED", "APPROUVÉ"),
                            ("REJECTED", "REJETÉ"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "name",
                    core.models.fields.charfield.CharField(
                        max_length=255, verbose_name="Nom du jour férié"
                    ),
                ),
                (
                    "start_date",
                    core.models.fields.datefield.DateField(
                        db_index=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    core.models.fields.datefield.DateField(
                        db_index=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Si activé, ce jour férié se répète chaque année aux mêmes dates.",
                        verbose_name="Récurrent",
                    ),
                ),
                (
                    "description",
                    core.models.fields.textfield.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "days",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Jours ouvrables"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jour férié",
                "verbose_name_plural": "Jours fériés",
                "ordering": ("-start_date",),
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="leave_holid_start_d_9c0238_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="holiday_valid_date_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "sub_organization",
                    core.models.fields.choice_field.ChoiceField(
                        blank=True,
                        choices=core.models.base.get_sub_organization_choices,
                        max_length=100,
                        null=True,
                        verbose_name="sous-organisation",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "start_date",
                    core.models.fields.datefield.DateField(
                        db_index=True, verbose_name="date de début"
                    ),
                ),
                (
                    "end_date",
                    core.models.fields.datefield.DateField(
                        db_index=True, verbose_name="date de fin"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="durée (jours)"
                    ),
                ),
                (
                    "status",
                    core.models.fields.charfield.CharField(
                        choices=[
                            ("PENDING", "EN ATTENTE"),
                            ("APPROVED", "APPROUVÉ"),
                            ("REJETÉ", "REJETÉ"),
                        ],
                        db_index=True,
                        default="PENDING",
                        editable=False,
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
                (
                    "reason",
                    core.models.fields.textfield.TextField(
                        blank=True, verbose_name="motif"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type_of_leave",
                    core.models.fields.model_select_field.ModelSelectField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="leave.typeofleave",
                        verbose_name="type de congé",
                    ),
                ),
            ],
            options={
                "verbose_name": "congé",
                "verbose_name_plural": "congés",
                "ordering": ("-start_date",),
                "indexes": [
                    models.Index(
                        fields=["employee", "type_of_leave", "status"],
                        name="leave_leave_employe_a0a10f_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="leave_valid_date_range",
                    )
                ],
            },
        ),
    ]
