# Generated by Django 5.1.3 on 2025-06-18 13:36

import core.models.fields.charfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earlyleave",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("PENDING", "EN ATTENTE"),
                    ("APPROVED", "APPROUVÉ"),
                    ("REJECTED", "REJETÉ"),
                ],
                default="PENDING",
                editable=False,
                max_length=10,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("PENDING", "EN ATTENTE"),
                    ("APPROVED", "APPROUVÉ"),
                    ("REJECTED", "REJETÉ"),
                ],
                default="PENDING",
                editable=False,
                max_length=10,
                verbose_name="statut",
            ),
        ),
    ]
