# Generated by Django 5.1.3 on 2026-01-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leave',
            name='leave_valid_date_range',
        ),
    ]
