# Generated by Django 5.1.3 on 2025-11-25 14:17

import core.models.base
import core.models.fields.booleanfield
import core.models.fields.charfield
import core.models.fields.choice_field
import core.models.fields.integerfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="number_of_days",
            field=core.models.fields.integerfield.IntegerField(
                default=0, editable=False, verbose_name="nombre de jour(s)"
            ),
        ),
        migrations.AlterField(
            model_name="earlyleave",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("PENDING", "EN ATTENTE"),
                    ("APPROVED", "APPROUVÉ"),
                    ("REJECTED", "REJETÉ"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="earlyleave",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="typeofleave",
            name="paid",
            field=core.models.fields.booleanfield.BooleanField(
                default=True, verbose_name="congé payé"
            ),
        ),
        migrations.AlterField(
            model_name="typeofleave",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
    ]
