# Generated by Django 5.1.3 on 2026-01-06 11:50

import core.models.fields.charfield
import core.models.fields.datefield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="holiday",
            options={
                "ordering": ("-start_date",),
                "verbose_name": "Jour férié",
                "verbose_name_plural": "Jours fériés",
            },
        ),
        migrations.AlterField(
            model_name="holiday",
            name="days",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Jours ouvrables"
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="end_date",
            field=core.models.fields.datefield.DateField(
                db_index=True, verbose_name="Date de fin"
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="is_recurring",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, ce jour férié se répète chaque année aux mêmes dates.",
                verbose_name="Récurrent",
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="name",
            field=core.models.fields.charfield.CharField(
                max_length=255, verbose_name="Nom du jour férié"
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="start_date",
            field=core.models.fields.datefield.DateField(
                db_index=True, verbose_name="Date de début"
            ),
        ),
    ]
