# Generated by Django 5.1.3 on 2026-01-08 09:44

import core.models.fields.foreignkey
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='type_of_leave',
            field=core.models.fields.foreignkey.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.typeofleave', verbose_name='type de congé'),
        ),
    ]
