# Generated by Django 5.1.3 on 2026-01-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_remove_leave_leave_valid_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='duration',
            field=models.IntegerField(default=0, editable=False, verbose_name='durée (jours)'),
        ),
    ]
