# Generated by Django 5.1.3 on 2025-12-14 06:11

import core.models.fields.charfield
import django.db.models.expressions
import leave.models.leave
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0002_leave_number_of_days_alter_earlyleave_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="number_of_days",
        ),
        migrations.AddField(
            model_name="leave",
            name="duration",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.ExpressionWrapper(
                    django.db.models.expressions.CombinedExpression(
                        leave.models.leave.Epoch(
                            django.db.models.expressions.CombinedExpression(
                                models.F("end_date"), "-", models.F("start_date")
                            )
                        ),
                        "/",
                        models.Value(86400),
                    ),
                    output_field=models.IntegerField(),
                ),
                output_field=models.IntegerField(
                    default=0, editable=False, verbose_name="durée (jours)"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("PENDING", "EN ATTENTE"),
                    ("APPROVED", "APPROUVÉ"),
                    ("REJETÉ", "Rejected"),
                ],
                default="PENDING",
                editable=False,
                max_length=10,
                verbose_name="statut",
            ),
        ),
    ]
