# Generated by Django 5.1.3 on 2025-08-22 19:01

import core.models.base
import core.models.fields.charfield
import core.models.fields.choice_field
import core.models.fields.foreignkey
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0004_alter_columnlevelsecurity_content_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approval",
            options={
                "verbose_name": "approbation",
                "verbose_name_plural": "approbations",
            },
        ),
        migrations.AddField(
            model_name="actionrequired",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("PENDING", "EN ATTENTE"),
                    ("APPROVED", "APPROUVÉ"),
                    ("REJECTED", "REJETÉ"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="actionrequired",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("PENDING", "EN ATTENTE"),
                    ("APPROVED", "APPROUVÉ"),
                    ("REJECTED", "REJETÉ"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="columnlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="columnlevelsecurity",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="key",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("DEFAULT_USER_ROLE:STR", "DEFAULT_USER_ROLE:STR"),
                    ("DEFAULT_USER_PASSWORD:STR", "DEFAULT_USER_PASSWORD:STR"),
                    ("DEFAULT_CHECK_IN_RANGE:LIST", "DEFAULT_CHECK_IN_RANGE:LIST"),
                    ("DEFAULT_CHECK_OUT_RANGE:LIST", "DEFAULT_CHECK_OUT_RANGE:LIST"),
                ],
                max_length=100,
                unique=True,
                verbose_name="clé",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="sub_organization",
            field=core.models.fields.choice_field.ChoiceField(
                blank=True,
                choices=core.models.base.get_sub_organization_choices,
                max_length=100,
                null=True,
                verbose_name="sous-organisation",
            ),
        ),
    ]
