# Generated by Django 5.1.3 on 2025-06-17 07:12

import core.models.fields.foreignkey
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0009_alter_columnlevelsecurity_content_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workflow",
            old_name="model",
            new_name="content_type",
        ),
        migrations.AlterField(
            model_name="approval",
            name="object_id",
            field=models.PositiveIntegerField(verbose_name="object ID"),
        ),
        migrations.AlterField(
            model_name="columnlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="approval",
            unique_together={("user", "status", "content_type", "object_id")},
        ),
    ]
