# Generated by Django 5.1.3 on 2025-06-17 11:26

import core.models.fields.ace_field
import core.models.fields.charfield
import core.models.fields.foreignkey
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0010_rename_model_workflow_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvé"),
                    ("rejected", "Rejeté"),
                ],
                default="pending",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="columnlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="condition",
            field=core.models.fields.ace_field.AceField(
                default="True",
                help_text='press "Ctrl+Space" to get code completionpress "Ctrl+M" to toggle in modal mode',
                verbose_name="condition applicable à ce workflow",
            ),
        ),
    ]
