# Generated by Django 5.1.3 on 2025-06-27 12:22

import core.models.fields.charfield
import core.models.fields.foreignkey
import core.models.fields.model_select_to_multiple_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0012_alter_columnlevelsecurity_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("PENDING", "EN ATTENTE"),
                    ("APPROVED", "APPROUVÉ"),
                    ("REJECTED", "REJETÉ"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="columnlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                help_text="Le modèle auquel cette règle de filtrage est associée.",
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                blank=True,
                help_text="Les groupes dont fait partie cet utilisateur. Celui-ci obtient tous les droits de tous les groupes auxquels il appartient.",
                to="core.group",
                verbose_name="groupes",
            ),
        ),
    ]
