# Generated by Django 5.1.3 on 2025-05-19 05:24

import core.models.fields.ace_field
import core.models.fields.charfield
import core.models.fields.datetimefield
import core.models.fields.foreignkey
import core.models.fields.jsonfield
import core.models.fields.model_select_field
import core.models.fields.model_select_to_multiple_field
import core.models.fields.positiveintegerfield
import core.models.fields.textfield
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0016_alter_fieldpermission_field_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpermission',
            name='field_content_type',
            field=core.models.fields.foreignkey.ForeignKey(default=None, help_text='Le modèle auquel cette règle de filtrage est associée.', limit_choices_to={'app_label__in': ['core', 'employee', 'payroll']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='type de contenu'),
        ),
        migrations.AlterField(
            model_name='rowlevelsecurity',
            name='row_content_type',
            field=core.models.fields.foreignkey.ForeignKey(default=None, help_text='Le modèle auquel cette règle de filtrage est associée.', limit_choices_to={'app_label__in': ['core', 'employee', 'payroll']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='type de contenu'),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_metadata', core.models.fields.jsonfield.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('updated_at', core.models.fields.datetimefield.DateTimeField(auto_now=True, verbose_name='mis à jour le/à')),
                ('created_at', core.models.fields.datetimefield.DateTimeField(auto_now_add=True, verbose_name='créé le/à')),
                ('name', core.models.fields.charfield.CharField(max_length=100, verbose_name='nom')),
                ('condition', core.models.fields.ace_field.AceField(default='None', help_text='press "Ctrl+Space" to get code completionpress "Ctrl+M" to toggle in modal mode', verbose_name='condition applicable à ce workflow')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('model', core.models.fields.model_select_field.ModelSelectField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='modèle associé')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
                ('users', core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(to=settings.AUTH_USER_MODEL, verbose_name='validateur(s)')),
            ],
            options={
                'verbose_name': 'workflow',
                'verbose_name_plural': 'workflows',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', core.models.fields.positiveintegerfield.PositiveIntegerField(verbose_name='object id')),
                ('status', core.models.fields.charfield.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='status')),
                ('comment', core.models.fields.textfield.TextField(blank=True, default=None, null=True, verbose_name='comment')),
                ('content_type', core.models.fields.model_select_field.ModelSelectField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='model')),
                ('user', core.models.fields.model_select_field.ModelSelectField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='approver')),
                ('workflow', core.models.fields.model_select_field.ModelSelectField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workflow', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'approval',
                'verbose_name_plural': 'approvals',
            },
        ),
    ]
